version: '3'

services:
  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./php-fpm/log:/var/log
      - ../einvoice:/var/www/html/einvoice
      - ../kfin:/var/www/html/kfin
    depends_on:
      - einvoice-operation
      - einvoice-backend
      - einvoice-search-api
#      - kfcrm
    networks:
      - app-network
    restart: unless-stopped

  # PHP-FPM Service (PHP 8.2)
  einvoice-operation:
    build:
      context: ./php-fpm
      dockerfile: php82.dockerfile
    container_name: einvoice-operation
    volumes:
      - ../einvoice/einvoice-operation:/var/www/html/einvoice/einvoice-operation
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network
    restart: unless-stopped

  einvoice-backend:
    platform: linux/amd64
    build:
      context: ./php-fpm
      dockerfile: php74-mssql.dockerfile
    container_name: einvoice-backend
    volumes:
      - ../einvoice/kv-einvoice-backend:/var/www/html/einvoice/kv-einvoice-backend
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - app-network
    restart: unless-stopped

  einvoice-search-api:
    platform: linux/amd64
    build:
      context: ./php-fpm
      dockerfile: php74-mssql.dockerfile
    container_name: einvoice-search-api
    volumes:
      - ../einvoice/kv-einvoice-search-api:/var/www/html/einvoice/kv-einvoice-search-api
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      - "PHP_IDE_CONFIG=serverName=einvoice-search-api"
      - "XDEBUG_CONFIG=client_host=host.docker.internal log=/var/log/xdebug.log"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network
    restart: unless-stopped

  # PHP-FPM Service (PHP 7.4)
#  kfcrm:
#    build:
#      context: ./php-fpm
#      dockerfile: php74.dockerfile
#    container_name: kfcrm
#    volumes:
#      - ../kfin/kfcrm:/var/www/html/kfin/kfcrm
#      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
#    networks:
#      - app-network
#    restart: unless-stopped

  # Node.js 20
  node20:
    build:
      context: ./node
      dockerfile: node20.dockerfile
    container_name: node20
    working_dir: /var/www/html
    volumes:
      - ../einvoice:/var/www/html/einvoice
    networks:
      - app-network
    tty: true

  # MariaDB Service
  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  mariadb-data:
    driver: local
  redis-data:
    driver: local
  mongodb-data:
    driver: local
